### ISSUE TITLE
Issues setting up on device

### ISSUE THREAD

**Issue by rkomiyama** [arnif/sonarr-native#26]
After running `react-native run-android`, I get this error message on my device (Nexus 6, stock ROM, version 6.0.1).

![screenshot_20161004-211354](https://cloud.githubusercontent.com/assets/347483/19098098/75a95d34-8a78-11e6-8734-d2f90b98e804.png)

**Comment by arnif** [comment]
I don't have android emulator setup so I've not run the project in an android emulator but I @ikornaselur has maybe he can provide some information ?

But I know this solves a lot of problems:

```
brew update
brew reinstall watchman
```

Also did you run the command it says there, `adb reverse tcp:8081 tcp:8081` ?

**Comment by ikornaselur** [comment]
Hm, this definitely sounds like it's either not being able to connect to the development server or that it's not running. If it's not able to connect, following the instructions on the screen should suffice.

Are you sure that it is running? You can start the dev server manually with `react-native start` before running `react-native run-android`, but running the second command should start by running the dev server anyway.

If making sure the dev server is up and running and trying to run the `adb reverse` command if connected no USB doesn't work, then more info would be appreciated, for example, does it work on the emulator instead of device? Also what operating system are you running this from?

**Comment by rkomiyama** [comment]
@arnif I've tried that, and when I run `adb reverse --list`, I get `(null) tcp:8081 tcp:8081`.

@ikornaselur I'll run `react-native start` first and see how that goes! I haven't tried running this on an emulator. I'm running Windows 10.

**Comment by rkomiyama** [comment]
By running `react-native start` first, I was able to get my device to open the app's configuration page. Without changing the values of the address or key, I click "Save". After that, I get this error message in the image. I guess it's because I need to specify an IP address. Do I use the IP address of my Windows machine?

![screenshot_20161007-161726](https://cloud.githubusercontent.com/assets/347483/19204261/c2ce3728-8ca9-11e6-8487-869c0515882b.png)

**Comment by arnif** [comment]
Yes the IP address of your Sonarr Instance (`http://<ip-address>:<port>`).

I guess we should add some check and not allow empty input when a user presses Save.

**Comment by rkomiyama** [comment]
@arnif I've tried saving my Windows machine's IP, and I get this error message after a few minutes of waiting.

![screenshot_20161007-171453](https://cloud.githubusercontent.com/assets/347483/19205643/b8b93c80-8cb1-11e6-95ab-e22dbc68a472.png)

**Comment by arnif** [comment]
hmm do you have sonarr running locally ? also the API key needs to be valid. You can use this instance to test stuff:

IP: `http://139.59.166.50:8989`
API key: `5287e9314d904a499739187b8dd38c08`

**Comment by rkomiyama** [comment]
@arnif I did not have it running, oops. I started Sonarr, but I still had the same exact issue. However, I tried the instance that you mentioned and that worked just fine.

**Comment by arnif** [comment]
Ok just double check the IP address and make sure no extra params are in the url and check the API key is correct (You can see it under  [Settings -> General](http://139.59.166.50:8989/settings/general). 

Please note the Sonarr instance I have for testing is very limited and there is no Torrent client setup so Downloading does not work.

Thank you for showing this project interest and I will gladly accept any PR that will improve this project.
