### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by arnif** [arnif/sonarr-native#31]
The current Icon is just the Sonarr icon which we should have something else inspired by that icon. Pretty sure we can't have the same icon.

Also a Beta and Alpha version of the Icon would be appreciated.

**Comment by daviditsygin** [comment]
I can do this in a few hours.

**Comment by arnif** [comment]
That would be awesome ! Thank you.

**Comment by daviditsygin** [comment]
Sorry haven't quite gotten around to this yet. I will make sure to get this done asap.

**Comment by daviditsygin** [comment]
My attempt is in #32

**Comment by arnif** [comment]
Thank you very much !
