### ISSUE TITLE
Update to latest version of React-native

### ISSUE THREAD

**Issue by arnif** [arnif/sonarr-native#35]
Version 0.33 of react-native has some important updates to make the project compile without any hassle on macOS Sierra

https://github.com/facebook/react-native/issues/8584#issuecomment-236366222

Here is a link to the upgrade guide: https://facebook.github.io/react-native/docs/upgrading.html

**Comment by arnireynir** [comment]
I will do it 💯

**Comment by redbmk** [comment]
@arnireynir Have you started on this? I should have at least commented on it but I started working on this yesterday and am nearly done. I just need to test it out. I didn't know you could assign tasks either.

**Comment by arnif** [comment]
He was going to start on this later today. So you are welcome to finish this.

**Comment by redbmk** [comment]
OK cool, sorry about the confusion

**Comment by arnif** [comment]
No problem and thank you for showing this project interest 😊

**Comment by redbmk** [comment]
Yeah it looks cool. I'm on Android so maybe I can help with some of that as well. But I'll need you guys to double check that it works on iOS after the upgrade...I don't have a mac or ios device.

One thing I noticed is they changed the code to make insecure websites not work by default, so I kept it the old way assuming not everyone is running sonarr with https. But if we want to require that for security I can merge that new code in.

**Comment by redbmk** [comment]
On iOS that is...

**Comment by arnif** [comment]
Yes lets not force user to use https for their Sonarr instance. And yes I'll double check once you have it ready :)

**Comment by redbmk** [comment]
Please give this a shot when you get a chance and let me know if you run into any issues. I tried it on android and didn't notice any differences from before.

**Comment by arnif** [comment]
Perfect ! thank you 😎
